apiVersion: v1
kind: Service
metadata:
  name: monitoring-logging-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30010
  selector:
    app: monitoring-demo-app
