name: Container Security Scan 

on:
  push:
    branches: [ "demo" ]
  pull_request:

jobs:
  image-scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Build Docker image
      - name: Build Docker image
        run: docker build -t devsecops-app:latest .

      # Run Trivy scan
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devsecops-app:latest'
          format: 'table'               # Options: table, json, sarif, template
          exit-code: '1'                # Fail if vulnerabilities are found
          ignore-unfixed: true          # Ignore vulnerabilities with no fix
          vuln-type: 'os,library'       # Scan both OS packages & libraries
          severity: 'CRITICAL,HIGH'     # Fail only on CRITICAL/HIGH
